### ISSUE TITLE
How to convert 'element.Name == W.oMath' ?

### ISSUE THREAD

**Issue by renshou2003** [Codeuctivity/OpenXmlToHtml#74]
How to convert 'element.Name == W.oMath' ?

**Comment by stesee** [comment]
Looks like no one built a translation from OpenXml oMath to something that can be used in HTML - https://github.com/Codeuctivity/OpenXmlPowerTools/blob/f0a8266874c2d9e91a9a69d7b680a82e70029d55/OpenXmlPowerTools/OpenXMLWordprocessingMLToHtmlConverter/WmlToHtmlConverter.cs#L426 . A translation of oMath would be great, but I have no spare time for implemening such a conversion by my self/alone.... if you like to add an PR to https://github.com/Codeuctivity/OpenXmlPowerTools it would probably get into some release in the future
