### ISSUE TITLE
Bug when converting text containing a tab character inside a paragraph

### ISSUE THREAD

**Issue by orlfi** [Codeuctivity/OpenXmlToHtml#78]
If you insert a tab character between words within a paragraph, then the HTML page will be distorte
![docx in word](https://user-images.githubusercontent.com/48785414/176391280-15ddb34d-bb4a-4acf-932e-583cde1c801c.png)
![html](https://user-images.githubusercontent.com/48785414/176391289-1db5505b-8589-4ae5-ba66-c5e8a6853f97.png)
d

**Comment by orlfi** [comment]
[1.docx](https://github.com/Codeuctivity/OpenXmlToHtml/files/9008775/1.docx)
[1.html.zip](https://github.com/Codeuctivity/OpenXmlToHtml/files/9008783/1.html.zip)

**Comment by orlfi** [comment]
Is it possible to correctly convert text with tab characters inside a paragraph?

**Comment by stesee** [comment]
I can reproduce the bahavior. I will try to look into the possibility of a fix as soon as I have some spare time.

**Comment by orlfi** [comment]
Thanks!
Please update the nuget package
[https://www.nuget.org/packages/OpenXmlToHtml/#readme-body-tab](url)
